Feature/background
Ki-won/bcsd_beginner_project pull request #2
Opened 2022-03-01 06:31 UTC by Ki-won

add background feature -> devlop feature

2022-03-06 07:03 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/HomeScreenAdapter.kt
> +        fun bind(innerlist:MutableList<Int>){
함수 내에서 리스트의 수정이 이뤄지지 않는데, 이럴 경우 `MutableList` 대신 `List` 사용을 권합니다

2022-03-06 07:05 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/HomeScreenAdapter.kt
> +    val itemList : MutableList<MutableList<Int>>
클래스 내에서 리스트의 내용을 변경하지 않을 경우, `MutableList` 대신 `List` 사용을 권합니다.

2022-03-06 07:07 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/HomeScreenAdapter.kt
> +        fun onClick(v: View, position: Int, lottery:MutableList<Int>)
Listener에서 변경 가능한 리스트를 보낼 이유는 없다고 생각합니다. 클래스나 함수 등을 만들 때, 함수를 잘 정의하여 다른 사람이 사용할 때 의도하지 않는 동작(여기서는 리스트 내용 변경)을 최소화하는 것이 좋습니다.

2022-03-06 07:07 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/MyWinningAdapter.kt
> +class MyWinningAdapter(
`HomeScreenAdapter` 의 코멘트 참조해서 `MutableList` 관련 리팩토링 진행해 주세요

2022-03-06 07:08 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenAdapter.kt
> +    private  lateinit var mainViewModel: MainViewModel
띄어쓰기 두칸, 15,16번째 라인의 불필요한 공백 정리 바랍니다.

2022-03-06 07:09 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenAdapter.kt
> +    private val _items = mutableListOf<TodayLotteryNumber>()//개인 유저 정보 등수 , 당첨금
주석 없이 변수의 용도를 이해할 수 있도록 변수 이름을 조정해 보는건 어떨까요?

2022-03-06 07:09 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenAdapter.kt
> +       */
불필요한 주석 제거 바랍니다.

2022-03-06 07:12 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            .get(MainViewModel::class.java)
activity ktx, fragment ktx 라이브러리 추가 후 Property Delegation을 이용해서 이 코드를 생략할 수 있습니다.

```Kotlin
private val mainViewModel: MainViewModel by viewModels()
```

2022-03-06 07:14 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +        val pastwinningnumbersObserver = Observer<MutableList<Int>> {
네이밍 컨벤션 지켜주세요

2022-03-06 07:14 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            var edittextdate = binding.editText.text.toString()
네이밍 컨벤션 지켜주세요

2022-03-06 07:18 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            val it_list = it
이렇게 한 이유가 있을까요? 만약 `it` 이름이 여러개라 혼동을 피하려고 이렇게 했다면
```kotlin
val pastwinningnumbersObserver = Observer<MutableList<Int>> { winningNumbers -> /* ... */ }
```
와 같은 방법으로 `it` 대신에 다른 이름을 사용할 수 있습니다.

2022-03-06 07:20 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +                    Toast.makeText(view?.context, "$count 개 일치!", Toast.LENGTH_SHORT).show()
`requireContext()` 또는 Fragment에 정의된 getContext() 함수를 사용하는 것을 추천드립니다

2022-03-06 07:21 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +                    val pastnumbers = Observer<MutableList<Int>> {
`pastlotterynumbers`, `allusernumberlist`, `pastnumbers` 네이밍 컨벤션 지켜주세요

2022-03-06 07:21 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            var allusernumberlist = homeScreenViewModel.makeTwoDimensionalList(it)
Observer 내에서 이 변수의 수정이 일어나지 않는 것 같은데, `val` 키워드 사용을 권합니다

2022-03-06 07:22 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            var allusernumberlist = homeScreenViewModel.makeTwoDimensionalList(it)
네이밍 컨벤션 지켜주세요. 또한 Observer 내에서 이 변수의 수정이 일어나지 않는 것 같은데, val 키워드 사용을 권합니다.

2022-03-06 07:23 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            var todayWinningNumbers = it
`HomeScreenFragment` 의 `it_list` 관련 코멘트 확인해서 수정해주세요

2022-03-06 07:24 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +    private fun checkWinningRanking(
함수 내부 네이밍 컨벤션 지켜주세요.

2022-03-06 07:25 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +        alluserlist: MutableList<MutableList<Int>>,
리스트의 내용 변경을 하지 않는 것으로 보이는데, `MutableList` 대신 `List` 사용을 권합니다

2022-03-06 07:25 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +        var winnerhistory = mutableListOf<Int>(0, 0, 0, 0, 0, 0, 0, 0)
`val` 키워드 사용해도 될 것 같습니다

2022-03-06 07:26 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenViewHolder.kt
> + */
불필요한 주석 제거해 주세요

2022-03-06 07:28 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/model/LotteryNumber.kt
> +    @SerializedName("date") var date:String
`data class`는 프로퍼티를 모두 `val`로 선언하여 final하게 만드는 것을 권장합니다. 한 `LotteryNumber` 객체에서 내부 데이터 수정이 어려워지면 관리가 어려워지기 때문입니다. 만약 객체 내부 값을 변경해야 한다면 copy 메소드를 이용해서 값이 변경된 새로운 객체를 만드는 것이 좋습니다.

2022-03-06 07:29 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/model/TodayLotteryNumber.kt
> +data class TodayLotteryNumber(
`LotteryNumber`의 코멘트 참조해서 `var` 키워드 수정해 주세요.

2022-03-06 07:30 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/test.kt
> +}
이 파일은 무슨 용도로 존재하는 건가요?

2022-03-06 07:31 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/view/MyWinningActivity.kt
> +        val myLotteryNumbers = intent.getStringExtra("myLotteryNumbers") // 나의 로또 번호 문자열
Activity Result API 사용해서 인텐트 변수 관리를 더 깔끔하게 할 수 있습니다.

2022-03-06 07:35 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/view/MyWinningActivity.kt
> +    private fun createMyLotteryNumbers(myLotteryNumbers: String): MutableList<MutableList<Int>> {
이 함수를 사용할 때 로또 번호 리스트의 내용을 수정할 일이 있을까요?

2022-03-06 07:37 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/view/MyWinningActivity.kt
> +        var myrandnumberlist = mutableListOf<MutableList<Int>>()
네이밍 컨벤션 및 `MutableList`, `var` 키워드 수정 바랍니다

2022-03-06 07:39 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/view/MyWinningActivity.kt
> +    private fun createAdapter(myrandnumberlist: MutableList<MutableList<Int>>) {
네이밍 컨벤션 및 `MutableList` 확인해주세요

2022-03-06 07:39 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/view/MyWinningActivity.kt
> +                var count_list = arrayListOf<Int>()
`var` 키워드 및 네이밍 컨벤션 확인해주세요

2022-03-06 07:54 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
> +    val pastdate = MutableLiveData<String>()
```Kotlin
private val _pastDate = MutableLiveData<String>()
val pastDate : LiveData<String> get() = _pastDate
```
와 같은 방법으로 viewmodel 외부에서 livedata의 값 변경이 일어나지 않도록 하는것이 좋습니다.

12~15라인 네이밍 컨벤션 및 `MutableList` 확인해주세요

2022-03-06 07:56 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
> +    fun pastDateUserDataMatching(edittextdate: String, context: Context?) {
viewmodel에서 android context를 함수 인자로 넘기거나 저장해 두는 것은 하지 않는 게 좋습니다. 토스트 메시지에 context를 사용하는데, 토스트 메시지를 띄우는 것은 view가 담당하는 내용입니다

2022-03-06 07:57 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
> +    fun makeTwoDimensionalList(stringnumber: String): MutableList<MutableList<Int>> {
`MutableList` 및 코드 컨벤션 확인해주세요.

2022-03-06 07:57 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
> +    fun pastWinningData(pastlist: MutableList<Int>) {
`MutableList` 및 코드 컨벤션 확인해 주세요.

2022-03-06 07:58 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/MainViewModel.kt
> +    val date = MutableLiveData<String>() // 당첨 날짜
`HomeScreenViewModel`의 코멘트 내용을 참고해서 `MutableLiveData` 관련 내용 수정해주세요

2022-03-06 07:59 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/MainViewModel.kt
> +    fun updateData(key: String, value: Any, context: Context) {
`HomeScreenViewModel`의 코멘트 내용을 참고해서 `context`를 사용하지 않도록 코드 수정해주세요

2022-03-06 08:00 UTC, Yang-Seungmin commented on app/src/main/res/layout/activity_sign_in.xml
> +            android:id="@+id/sign_in_title"
`sign_in_title_text_view`로 수정하는 것이 좋을 것 같습니다.

2022-03-06 08:00 UTC, Yang-Seungmin commented on app/src/main/res/layout/activity_sign_in.xml
> +            android:id="@+id/up_get_user_password_edit_view"
`up_get_user_password_edit_text`로 수정하는 것이 좋을 것 같습니다.

2022-03-06 08:01 UTC, Yang-Seungmin commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:id="@+id/sign_up_title"
`sign_up_title_text_view`로 수정하는 것이 좋을 것 같습니다.

2022-03-06 08:01 UTC, Yang-Seungmin commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:id="@+id/up_get_user_email_edit_view"
`up_get_user_email_edit_text`로 수정하는 것이 좋을 것 같습니다.

2022-03-06 08:01 UTC, Yang-Seungmin commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:id="@id/up_get_user_password_edit_view"
`up_get_user_password_edit_text`로 수정하는 것이 좋을 것 같습니다.

2022-03-06 08:01 UTC, Yang-Seungmin commented on app/src/main/res/layout/activity_sign_up.xml
> +            android:id="@+id/up_get_user_name_edit_view"
`up_get_user_name_edit_text`로 수정하는 것이 좋을 것 같습니다.

2022-03-06 08:03 UTC, Yang-Seungmin commented on app/src/main/res/values/colors.xml
> +    <color name="lightYellow">#ECEAD6</color>
`light_yellow`로 수정해 주세요

2022-03-06 08:03 UTC, Yang-Seungmin commented on app/src/main/res/values/strings.xml
> +    <string name="myPage">MyPage</string>
`my_page`로 수정해 주세요

2022-03-06 08:04 UTC, Yang-Seungmin requested changes
전반적인 코드 컨벤션, `val`및 `var` 키워드의 적절한 사용, `MutableList`및 `List`의 적절한 사용이 되어있지 않습니다.

2022-03-06 08:05 UTC, Yang-Seungmin reviewed
Conflict 수정해주세요

2022-03-06 15:52 UTC, Ki-won commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/HomeScreenAdapter.kt
> +    val itemList : MutableList<MutableList<Int>>
done

2022-03-06 15:53 UTC, Ki-won commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/HomeScreenAdapter.kt
> +        fun bind(innerlist:MutableList<Int>){
done

2022-03-06 15:54 UTC, Ki-won commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/HomeScreenAdapter.kt
> +        fun onClick(v: View, position: Int, lottery:MutableList<Int>)
done

2022-03-06 16:00 UTC, Ki-won commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/adapter/MyWinningAdapter.kt
> +class MyWinningAdapter(
done

2022-03-06 16:01 UTC, Ki-won commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenAdapter.kt
> +    private val _items = mutableListOf<TodayLotteryNumber>()//개인 유저 정보 등수 , 당첨금
items 를 각각의 역할에 맞춰 numberItems, userItems로 변경

2022-03-06 19:15 UTC, Ki-won commented
Conflict 수정완료...

2022-03-07 10:59 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            var todayWinningNumbers = winningNumbers
`winningNumbers -> ` 대신 `todayWinningNumbers -> `를 사용하면 불필요한 코드를 줄일 수 있겠네요

2022-03-07 10:59 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +            val listIt = it
`Observer<MutableList<Int>> { listIt -> ` 으로 코드를 줄일 수 있겠네요. 그리고 `listIt` 이 의미하는 내용이 뭔지 정확하게 알 수 있도록 변수명 수정이 필요해 보입니다

2022-03-07 11:01 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/homeFragment/HomeScreenFragment.kt
> +        allUserList.forEach { list_it ->
람다 매개변수 이름도 코드 컨벤션을 지켜야 합니다 (`list_it` -> `user`)

2022-03-07 11:04 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
> +    val currentAllUserLotteryNumbers = _currentAllUserLotteryNumbers
이렇게하면 외부에서 접근 가능한 `currentAllUserLotteryNumbers`가 `MutableList<String>` 타입을 가지게 됩니다. 변수의 타입을 생략하지 않고 지정해 주세요

2022-03-07 11:05 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
> +                        val int_list = mutableListOf<Int>()
코드 컨벤션 확인해 주세요

2022-03-07 11:05 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
>                          val str_list = masternumber.split(" ") as MutableList<String>
코드 컨벤션 확인해 주세요

2022-03-07 11:05 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/HomeScreenViewModel.kt
> +                        val customernumber = value.child("customer").value.toString()
코드 컨벤션 확인해 주세요

2022-03-07 11:06 UTC, Yang-Seungmin commented on app/src/main/java/com/bcsd/android/lotteryticketapplication/view/viewmodel/MainViewModel.kt
> +    val email = _email
`HomeScreenViewModel` 코멘트 참조해서 변경해 주세요

2022-03-07 11:08 UTC, Yang-Seungmin requested changes
의미있는 이름 사용, 코드 컨벤션 조금 더 연습하시면 잘할 수 있을거라 생각합니다

2022-03-07 14:19 UTC, Yang-Seungmin approved these changes
LGTM

2022-03-07 14:19 UTC, merged